# Generated by Django 5.2.10 on 2026-01-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('idVenda', models.AutoField(primary_key=True, serialize=False)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Atendente',
            new_name='Vendedor',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='fornecedor',
        ),
        migrations.RenameField(
            model_name='prateleira',
            old_name='genero',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='prateleira',
            old_name='numero',
            new_name='numPrateleira',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='prateleira',
        ),
        migrations.RemoveField(
            model_name='prateleira',
            name='capacidade',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='qtdEstoque',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
