# Generated by Django 5.2.10 on 2026-01-13 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_venda_rename_atendente_vendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='prateleira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prateleira'),
        ),
    ]
