# Generated by Django 5.2.10 on 2026-01-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_livro_prateleira'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='livros',
            field=models.ManyToManyField(related_name='vendas', to='core.livro'),
        ),
    ]
